config/routes.rb
Debutante::Application.routes.draw do
  root to: 'home#index'
  match '/auth/:provider/callback', to: 'sessions#create'  
  match '/auth/failure', to: 'sessions#failure'
  match '/signout', to: 'sessions#destroy', as: :signout
  match '/signin', to: 'sessions#new', as: :signin
  resources :projects, only: [:index, :new, :create]
  match '/projects/available_projects', to: 'projects#available_projects', as: :available_projects
  match '/projects/:id/vote', to: 'projects#vote'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :short_description, :title, :user_id, :votes, :url
  belongs_to :user

  validates :user_id, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :github_name, :has_voted
  has_many :projects

  def available_projects(token)
    GithubProjectLoader::getUserProjects(self.github_name, token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?
  helper_method :github_token

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue ActiveRecord::RecordNotFound
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:user_id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

    def github_token
      session[:github_token]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to projects_path
    end
  end
end

app/controllers/projects_controller.rb
require 'github_projects'

class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @projects = Project.order('votes DESC').all
  end

  def available_projects
    @github_projects = current_user.available_projects session[:github_token]
  end

  def new
    @project = Project.new(title: params[:project_name], url: params[:project_url])
  end

  def create
    @project = Project.new(title: params[:title], url: params[:url], description: params[:project][:description], short_description: params[:project][:description].slice(0..140))
    @project.user = current_user
    if !@project.save
      redirect_to({action: :index}, alert: "You have already submitted a project this round. Feel free to submit this one next week!")
    else
      redirect_to action: :index
    end
  end

  def vote
    if current_user.has_voted
      redirect_to({action: :index}, alert: "You have already voted this round. Feel free to vote again next week!")
    else
      Project.transaction do
        @project = Project.find(params[:id])
        @project.votes += 1
        current_user.has_voted = true
        @project.save
        current_user.save
      end
      redirect_to action: :index
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth_user = User.where(github_name: auth_hash.info.nickname).first_or_create(has_voted: false)
    session[:user_id] = auth_user.id
    session[:github_token] = auth_hash.credentials.token
    puts "Auth Hash: #{auth_hash.inspect}"
    redirect_to root_url
  end

  def failure
    redirect_to root_url, alert: "Authentication error: #{params[:message].humanize}"
  end

  def new
    redirect_to '/auth/github'
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'Signed out!'
  end

  protected
    def auth_hash
      request.env['omniauth.auth']
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class(name)
    case name.to_s
    when "notice"
      "alert alert-success"
    when "alert"
      "alert alert-error"
    else
      "alert"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.haml
.row
  .span12
    .hero-unit
      %h1 Debutante
      %p A weekly popularity contest on GitHub
      %p
        %a.btn.btn-primary.btn-large{:href => "/auth/github"}
          Sign in with
          your GitHub account

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en'}
%head
  %meta{charset: 'utf-8'}
  %title Debutante
  = stylesheet_link_tag "application", media: "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  .navbar
    .navbar-inner
      .container
        = link_to "Debutante", root_url, class: 'brand'
        - if user_signed_in?
          = link_to "Sign Out", signout_path, class: "btn btn-inverse pull-right"
          %p.navbar-text.pull-right
            Logged in as 
            = current_user.github_name
  .container
    .row
      .span12
        - flash.each do |name, msg|
          %div{class: alert_class(name)}
            %button.close{data: {dismiss: "alert"}}×
            = msg
    = yield

app/views/projects/available_projects.html.haml
%h1 Submit a project
%h2 Your projects:
%ul
  - @github_projects.each do |project|
    %li= link_to project.name, new_project_path(project_name: project.name, project_url: project.url)

app/views/projects/index.html.haml
.row
  .span12
    %h1 Project List
    = link_to("Submit a project", available_projects_path)
    - if @projects.empty?
      %p No projects have been submitted this week.
    - else
      %ul.project-list
        - @projects.each do |project|
          %li
            .project-row
              .vote-count= project.votes
              = link_to "Vote", "/projects/#{project.id}/vote", class: "btn btn-primary btn-small"
              .project-title= project.title
            %p= project.short_description

app/views/projects/new.html.haml
%h1 Submit Project
%h3= @project.title
= link_to @project.url, @project.url
= form_for @project, url: { action: "create" } do |f|
  = hidden_field_tag 'title', @project.title
  = hidden_field_tag 'url', @project.url
  = f.text_area :description, size: "60x12"
  = f.submit "Submit Project"